# Generated by Django 5.0.1 on 2026-02-06 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this analysis",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        help_text="GitHub repository URL to analyze",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("recruiter", "Recruiter"),
                            ("developer", "Developer"),
                        ],
                        default="recruiter",
                        help_text="Type of user requesting the analysis",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the analysis",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the analysis was requested",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the analysis processing began",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the analysis finished", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if analysis failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
                "db_table": "analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="analyses_created_ca7368_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this report",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        help_text="Final weighted score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "architecture_score",
                    models.FloatField(
                        help_text="Architecture pattern quality score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        help_text="Code quality metrics score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "principles_score",
                    models.FloatField(
                        help_text="SOLID principles adherence score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "collaboration_score",
                    models.FloatField(
                        help_text="Team collaboration metrics score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=dict,
                        help_text="AI-generated insights and recommendations",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict, help_text="Complete structured analysis data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the report was generated",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification time"
                    ),
                ),
                (
                    "analysis",
                    models.OneToOneField(
                        help_text="The analysis request this report belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="domain.analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
