# Generated by Django 5.0.1 on 2026-02-07 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="AI confidence in assessment (0.0-1.0)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_developer_guide",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Personalized developer improvement roadmap",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_executive_summary",
            field=models.TextField(
                blank=True,
                help_text="Executive summary with hiring recommendation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_hire_recommendation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hiring recommendation: Strong Yes/Yes/Maybe/No/Strong No",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_processing_time_ms",
            field=models.FloatField(
                blank=True,
                help_text="Total AI processing time in milliseconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_provider_used",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AI provider used (groq, openai, anthropic)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_total_tokens",
            field=models.IntegerField(
                blank=True, help_text="Total tokens used across all AI calls", null=True
            ),
        ),
    ]
